@startuml

Class Industry{
Name
}

Class StockPrize{
Price
PriceChange
PriceDate
}

Class Stock{
Name
}

Class StockRisk{
Rating
Profile
RiskDate
}


Industry "1"<--> "*"Stock
StockPrize "*"<--> "1" Stock
Stock "1"<--> "*"StockRisk

@enduml